-- AlterTable
ALTER TABLE `Admin_Profile` ADD COLUMN `First_Name` VARCHAR(191) NULL,
    ADD COLUMN `Last_Name` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `Doctor_Profile` ADD COLUMN `DOB` DATETIME(3) NULL,
    ADD COLUMN `First_Name` VARCHAR(191) NULL,
    ADD COLUMN `Gender` ENUM('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY') NULL,
    ADD COLUMN `Last_Name` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `Patient_Profile` ADD COLUMN `DOB` DATETIME(3) NULL,
    ADD COLUMN `First_Name` VARCHAR(191) NULL,
    ADD COLUMN `Gender` ENUM('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY') NULL,
    ADD COLUMN `Last_Name` VARCHAR(191) NULL;
